const ACTION = {
  read:   { color: '#4fa3ff', label: 'Read' },
  edit:   { color: '#ffb02e', label: 'Edit' },
  write:  { color: '#ff6b6b', label: 'Write' },
  bash:   { color: '#46d160', label: 'Bash' },
  agent:  { color: '#c58af9', label: 'Agent' },
  search: { color: '#9aa4b2', label: 'Search' },
  web:    { color: '#2dd4bf', label: 'Web' },
  other:  { color: '#818b98', label: 'Tool' },
};

const ICON = {
  read:   '<path d="M1.5 8s2.4-4.2 6.5-4.2S14.5 8 14.5 8s-2.4 4.2-6.5 4.2S1.5 8 1.5 8Z" fill="none" stroke="currentColor" stroke-width="1.4"/><circle cx="8" cy="8" r="1.9" fill="currentColor"/>',
  edit:   '<path d="m11.3 2.6 2.1 2.1L5.2 12.9l-2.7.6.6-2.7Z" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/>',
  write:  '<path d="M3.5 2.5h6l3 3v8h-9Z" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/><path d="M5.8 8h4.4M5.8 10.5h4.4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>',
  bash:   '<path d="m3 4.5 3.2 3.5L3 11.5M8.5 11.5H13" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
  agent:  '<circle cx="8" cy="8" r="2.3" fill="none" stroke="currentColor" stroke-width="1.4"/><path d="M8 1.8v2M8 12.2v2M1.8 8h2M12.2 8h2M3.6 3.6 5 5M11 11l1.4 1.4M3.6 12.4 5 11M11 5l1.4-1.4" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"/>',
  search: '<circle cx="7" cy="7" r="3.8" fill="none" stroke="currentColor" stroke-width="1.4"/><path d="m10 10 3.2 3.2" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>',
  web:    '<circle cx="8" cy="8" r="5.8" fill="none" stroke="currentColor" stroke-width="1.3"/><path d="M2.2 8h11.6M8 2.2c1.9 1.8 1.9 9.8 0 11.6M8 2.2c-1.9 1.8-1.9 9.8 0 11.6" fill="none" stroke="currentColor" stroke-width="1.1"/>',
  other:  '<circle cx="8" cy="8" r="1.8" fill="currentColor"/><circle cx="3.2" cy="8" r="1.4" fill="currentColor" opacity=".55"/><circle cx="12.8" cy="8" r="1.4" fill="currentColor" opacity=".55"/>',
};

const UP = '<path d="M8 2.5 13.5 9h-3.4v4.5H5.9V9H2.5Z"/>';

export function renderHTML(session) {
  const { events, files, model, startedAt, endedAt, sourcePath, usage } = session;
  const posts = buildPosts(events, startedAt);
  const toolCalls = events.filter(e => e.type === 'tool_call');
  const community = communityName(sourcePath);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>t/${escapeHtml(community)} · telltrace</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>${css()}</style>
</head>
<body>
${topbar(community)}
${banner(community, model, startedAt)}
<div class="shell">
  <main class="feed">
    <div class="sortbar">
      <button class="sort active" data-sort="hot">${flame()} Chronological</button>
      <button class="sort" data-sort="top">${UP_SVG()} Top</button>
      <span class="sortbar-right">${posts.length} posts</span>
    </div>
    <div id="posts">
      ${posts.map(renderPost).join('\n')}
    </div>
  </main>
  <aside class="rail">
    ${aboutCard(posts, toolCalls, files, usage, model, startedAt, endedAt)}
    ${activityCard(toolCalls, posts)}
    ${filesCard(files)}
    ${toolsCard(toolCalls)}
    <div class="rail-foot">
      Generated by <a href="https://github.com/mohamedkorain/telltrace">telltrace</a> · MIT
    </div>
  </aside>
</div>
<div class="tip" id="tip" hidden></div>
<script>${js()}</script>
</body>
</html>`;
}

/* --------------------------------- data shaping --------------------------------- */

function buildPosts(events, startedAt) {
  const t0 = startedAt ? Date.parse(startedAt) : NaN;
  const posts = [];
  let current = null;
  for (const e of events) {
    if (e.type === 'prompt') {
      current = { prompt: e, items: [] };
      posts.push(current);
    } else if (current && (e.type === 'tool_call' || e.type === 'assistant_text')) {
      current.items.push(e);
    }
  }
  if (posts.length === 0 && events.length > 0) {
    posts.push({ prompt: { text: '(session without captured prompt)', timestamp: null }, items: events.filter(e => e.type === 'tool_call' || e.type === 'assistant_text') });
  }

  return posts.map((p, i) => {
    const comments = threadify(p.items);
    const calls = p.items.filter(e => e.type === 'tool_call');
    const filesTouched = new Set(calls.filter(c => c.file).map(c => c.file));
    return {
      n: i + 1,
      prompt: p.prompt,
      comments,
      ops: calls.length,
      nFiles: filesTouched.size,
      offset: offsetLabel(p.prompt.timestamp, t0),
      t0,
    };
  });
}

function threadify(items) {
  const comments = [];
  let current = null;
  for (const e of items) {
    if (e.type === 'assistant_text') {
      if (!e.text?.trim()) continue;
      current = { text: e.text, timestamp: e.timestamp, runs: [] };
      comments.push(current);
    } else if (e.type === 'tool_call') {
      if (!current) {
        current = { text: null, timestamp: e.timestamp, runs: [] };
        comments.push(current);
      }
      const last = current.runs[current.runs.length - 1];
      if (last && last.tool === e.tool && last.action === e.action) {
        last.count++;
        if (e.file) last.files.add(e.file);
        if (e.args?.command) last.cmds.push(e.args.command);
      } else {
        current.runs.push({
          tool: e.tool,
          action: e.action ?? 'other',
          count: 1,
          files: new Set(e.file ? [e.file] : []),
          cmds: e.args?.command ? [e.args.command] : [],
          arg: summarizeArgs(e.tool, e.args),
        });
      }
    }
  }
  return comments;
}

/* ----------------------------------- chrome ----------------------------------- */

function topbar(community) {
  return `<header class="topbar">
  <div class="topbar-in">
    <a class="brand" href="#top">
      <svg class="mark" viewBox="0 0 24 24"><rect x="1" y="1" width="22" height="22" rx="11" fill="#ff4500"/><path d="M7 12.2h3l1.5-3.4 2 6.4 1.5-3.4H17" fill="none" stroke="#fff" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>
      <span class="brand-name">telltrace</span>
    </a>
    <div class="fakesearch mono">t/${escapeHtml(community)}</div>
    <span class="topbar-cta">agent session replay</span>
  </div>
</header>`;
}

function banner(community, model, startedAt) {
  return `<div class="banner" id="top">
  <div class="banner-art"></div>
  <div class="banner-in">
    <div class="sub-avatar">t/</div>
    <div class="banner-txt">
      <h1>t/${escapeHtml(community)}</h1>
      <div class="banner-sub">
        <span>u/claude &amp; u/you</span>
        ${model ? `<span class="dotsep"></span><span class="mono">${escapeHtml(model)}</span>` : ''}
        ${startedAt ? `<span class="dotsep"></span><span>${escapeHtml(formatDate(startedAt))}</span>` : ''}
      </div>
    </div>
  </div>
</div>`;
}

/* ------------------------------------ posts ------------------------------------ */

function renderPost(post) {
  const { title, body } = splitPrompt(post.prompt.text ?? '');
  const longBody = body.length > 500;
  const comments = post.comments.map(c => renderComment(c, post.t0)).join('');
  const nComments = post.comments.length;

  return `<article class="post" id="p${post.n}" data-ops="${post.ops}">
  <div class="gutter">
    <svg class="vote" viewBox="0 0 16 16">${UP}</svg>
    <span class="score" data-tip="${post.ops} tool calls">${post.ops}</span>
  </div>
  <div class="post-main">
    <div class="post-meta">
      <span class="avatar you">u</span>
      <span class="author">u/you</span>
      <span class="dotsep"></span>
      <span class="when mono">${escapeHtml(post.offset)}</span>
      ${post.nFiles ? `<span class="flair files-flair">${post.nFiles} ${post.nFiles === 1 ? 'file' : 'files'}</span>` : ''}
    </div>
    <h2 class="post-title">${escapeHtml(title)}</h2>
    ${body ? `<div class="post-body${longBody ? ' clamp' : ''}">${escapeHtml(body)}</div>${longBody ? '<button class="readmore" data-expand>Read more</button>' : ''}` : ''}
    <div class="post-actions">
      <button class="paction" data-collapse="c${post.n}">
        ${bubble()} <span>${nComments} ${nComments === 1 ? 'comment' : 'comments'}</span>
      </button>
      <span class="paction static">${bolt()} <span>${post.ops} ops</span></span>
    </div>
    <div class="thread" id="c${post.n}">
      ${comments || '<div class="no-comments">no agent activity</div>'}
    </div>
  </div>
</article>`;
}

function renderComment(c, t0) {
  const runs = c.runs.map(renderRun).join('');
  const off = offsetLabel(c.timestamp, t0);
  const body = c.text
    ? `<div class="c-body">${escapeHtml(truncate(c.text, 900))}</div>`
    : '';
  return `<div class="comment">
  <button class="threadline" data-fold aria-label="collapse"></button>
  <div class="c-main">
    <div class="c-meta">
      <span class="avatar claude">c</span>
      <span class="author claude-a">u/claude</span>
      <span class="dotsep"></span>
      <span class="when mono">${escapeHtml(off)}</span>
    </div>
    ${body}
    ${runs ? `<div class="runs">${runs}</div>` : ''}
  </div>
</div>`;
}

function renderRun(r) {
  const cfg = ACTION[r.action] ?? ACTION.other;
  let detail = '';
  if (r.action === 'bash' && r.cmds.length) {
    detail = r.cmds.length === 1 ? r.cmds[0] : `${r.cmds.length} commands`;
  } else if (r.files.size === 1) {
    detail = shortPath([...r.files][0]);
  } else if (r.files.size > 1) {
    detail = `${r.files.size} files`;
  } else if (r.arg) {
    detail = r.arg;
  }
  const tipParts = [`${r.tool}${r.count > 1 ? ` ×${r.count}` : ''}`];
  if (r.files.size) tipParts.push([...r.files].map(basename).slice(0, 8).join(', ') + (r.files.size > 8 ? '…' : ''));
  if (r.action === 'bash') tipParts.push(r.cmds.slice(0, 3).join(' && ').slice(0, 200));

  return `<div class="run" data-tip="${escapeHtml(tipParts.filter(Boolean).join(' · '))}">
    <span class="run-i" style="--c:${cfg.color}"><svg viewBox="0 0 16 16">${ICON[r.action] ?? ICON.other}</svg></span>
    <span class="run-tool">${escapeHtml(r.tool)}</span>
    ${r.count > 1 ? `<span class="run-n mono" style="--c:${cfg.color}">×${r.count}</span>` : ''}
    ${detail ? `<span class="run-d mono">${escapeHtml(truncate(detail, 88))}</span>` : ''}
  </div>`;
}

/* ------------------------------------ rail ------------------------------------ */

function aboutCard(posts, toolCalls, files, usage, model, startedAt, endedAt) {
  const tokens = usage ? usage.input + usage.output + usage.cacheRead + usage.cacheWrite : 0;
  const rows = [
    ['Prompts', posts.length],
    ['Tool calls', toolCalls.length],
    ['Files touched', files.length],
    ['Duration', formatDuration(startedAt, endedAt)],
  ];
  if (usage?.output) rows.push(['Tokens out', compact(usage.output)]);
  if (tokens) rows.push(['Tokens total', compact(tokens)]);

  return `<div class="card">
  <div class="card-head accent-head">About this session</div>
  <div class="card-pad">
    <div class="about-grid">
      ${rows.map(([l, v]) => `<div class="about-row"><span class="about-v">${escapeHtml(String(v))}</span><span class="about-l">${l}</span></div>`).join('')}
    </div>
  </div>
</div>`;
}

function activityCard(toolCalls, posts) {
  if (!toolCalls.length) return '';
  return `<div class="card">
  <div class="card-head">Activity</div>
  <div class="card-pad">${spark(toolCalls, posts)}</div>
</div>`;
}

function spark(toolCalls, posts) {
  const W = 280, H = 56;
  const times = toolCalls.map(c => Date.parse(c.timestamp)).filter(Number.isFinite);
  const useTime = times.length >= Math.max(2, toolCalls.length * 0.5);
  const buckets = 42;
  const counts = new Array(buckets).fill(0);
  const dom = new Array(buckets).fill(null).map(() => ({}));
  let t0 = 0, t1 = 1;
  if (useTime) { t0 = Math.min(...times); t1 = Math.max(...times); if (t1 === t0) t1 = t0 + 1; }
  toolCalls.forEach((c, i) => {
    const f = useTime && Number.isFinite(Date.parse(c.timestamp))
      ? (Date.parse(c.timestamp) - t0) / (t1 - t0)
      : i / Math.max(toolCalls.length - 1, 1);
    const b = Math.min(buckets - 1, Math.floor(f * buckets));
    counts[b]++;
    dom[b][c.action] = (dom[b][c.action] ?? 0) + 1;
  });
  const max = Math.max(...counts, 1);
  const bw = W / buckets;
  let bars = '';
  counts.forEach((n, i) => {
    if (!n) return;
    const h = Math.max(2.5, (n / max) * (H - 4));
    const a = Object.entries(dom[i]).sort((x, y) => y[1] - x[1])[0]?.[0] ?? 'other';
    bars += `<rect x="${(i * bw + 0.5).toFixed(1)}" y="${(H - h).toFixed(1)}" width="${(bw - 1.4).toFixed(1)}" height="${h.toFixed(1)}" rx="1" fill="${(ACTION[a] ?? ACTION.other).color}" opacity=".8" data-tip="${n} calls"/>`;
  });
  return `<svg viewBox="0 0 ${W} ${H}" class="sparksvg">${bars}</svg>
  <div class="spark-axis mono"><span>${useTime ? formatClock(t0) : 'start'}</span><span>${useTime ? formatClock(t1) : 'end'}</span></div>`;
}

function filesCard(files) {
  if (!files.length) return '';
  const ranked = [...files].sort((a, b) => b.events.length - a.events.length).slice(0, 8);
  const max = ranked[0].events.length;
  const rows = ranked.map((f, i) => `
    <div class="frow" data-tip="${escapeHtml(f.file)}">
      <span class="frank mono">${i + 1}</span>
      <span class="fname mono">${escapeHtml(truncate(basename(f.file), 26))}</span>
      <span class="fspark"><i style="width:${((f.events.length / max) * 100).toFixed(0)}%"></i></span>
      <span class="fcount mono">${f.events.length}</span>
    </div>`).join('');
  const more = files.length - ranked.length;
  return `<div class="card">
  <div class="card-head">Top files</div>
  <div class="card-pad tight">${rows}${more > 0 ? `<div class="more-note">+${more} more</div>` : ''}</div>
</div>`;
}

function toolsCard(toolCalls) {
  const counts = {};
  for (const c of toolCalls) counts[c.action ?? 'other'] = (counts[c.action ?? 'other'] ?? 0) + 1;
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  if (!entries.length) return '';
  const total = toolCalls.length;
  const segs = entries.map(([k, n]) => `<i style="flex:${n};background:${(ACTION[k] ?? ACTION.other).color}" data-tip="${(ACTION[k] ?? ACTION.other).label} · ${n} (${Math.round((n / total) * 100)}%)"></i>`).join('');
  const legend = entries.map(([k, n]) => `<span class="lg"><i style="background:${(ACTION[k] ?? ACTION.other).color}"></i>${(ACTION[k] ?? ACTION.other).label}<b>${n}</b></span>`).join('');
  return `<div class="card">
  <div class="card-head">Tool mix</div>
  <div class="card-pad">
    <div class="mixbar">${segs}</div>
    <div class="mixlegend">${legend}</div>
  </div>
</div>`;
}

/* ------------------------------------ css ------------------------------------ */

function css() {
  return `
:root {
  --bg: #0c0f11;
  --card: #14181b;
  --card-2: #191e22;
  --border: #22282d;
  --border-hi: #333b42;
  --text: #eef1f3;
  --dim: #939ba4;
  --faint: #5f6870;
  --orange: #ff4500;
  --blue: #4fa3ff;
  --claude: #d97757;
  --r: 14px;
  --mono: 'JetBrains Mono', ui-monospace, Menlo, monospace;
  --sans: 'Inter', -apple-system, 'Segoe UI', sans-serif;
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { margin: 0; background: var(--bg); color: var(--text); font: 400 14px/1.5 var(--sans); -webkit-font-smoothing: antialiased; }
a { color: var(--blue); text-decoration: none; }
a:hover { text-decoration: underline; }
.mono { font-family: var(--mono); }
.dotsep { width: 3px; height: 3px; border-radius: 50%; background: var(--faint); display: inline-block; margin: 0 2px; vertical-align: middle; }

.topbar { position: sticky; top: 0; z-index: 30; background: color-mix(in srgb, var(--bg) 88%, transparent); backdrop-filter: blur(12px); border-bottom: 1px solid var(--border); }
.topbar-in { max-width: 1128px; margin: 0 auto; display: flex; align-items: center; gap: 16px; height: 52px; padding: 0 16px; }
.brand { display: flex; align-items: center; gap: 8px; color: var(--text); }
.brand:hover { text-decoration: none; }
.mark { width: 26px; height: 26px; }
.brand-name { font-weight: 700; font-size: 15px; letter-spacing: -0.015em; }
.fakesearch { flex: 1; max-width: 480px; background: var(--card); border: 1px solid var(--border); border-radius: 999px; padding: 7px 16px; font-size: 12px; color: var(--dim); }
.topbar-cta { font-size: 12px; color: var(--faint); margin-left: auto; }

.banner { border-bottom: 1px solid var(--border); background: var(--card); }
.banner-art { height: 64px; background:
  radial-gradient(500px 90px at 15% 100%, rgba(255,69,0,0.22), transparent 65%),
  radial-gradient(600px 100px at 70% 100%, rgba(79,163,255,0.14), transparent 65%),
  linear-gradient(180deg, #171c20, #14181b); }
.banner-in { max-width: 1128px; margin: 0 auto; padding: 0 16px 14px; display: flex; gap: 14px; align-items: flex-end; transform: translateY(-18px); margin-bottom: -18px; }
.sub-avatar { width: 56px; height: 56px; border-radius: 50%; background: linear-gradient(135deg, var(--orange), #ff8717); border: 4px solid var(--card); display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 18px; color: #fff; flex-shrink: 0; }
.banner-txt h1 { margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.02em; }
.banner-sub { font-size: 12px; color: var(--dim); display: flex; align-items: center; gap: 6px; flex-wrap: wrap; margin-top: 2px; }

.shell { max-width: 1128px; margin: 0 auto; display: grid; grid-template-columns: minmax(0,1fr) 316px; gap: 20px; padding: 20px 16px 80px; align-items: start; }

.sortbar { display: flex; align-items: center; gap: 6px; background: var(--card); border: 1px solid var(--border); border-radius: var(--r); padding: 8px 12px; margin-bottom: 14px; }
.sort { display: inline-flex; align-items: center; gap: 6px; font: 600 12.5px var(--sans); color: var(--dim); background: none; border: none; border-radius: 999px; padding: 6px 12px; cursor: pointer; }
.sort svg { width: 15px; height: 15px; }
.sort:hover { background: var(--card-2); color: var(--text); }
.sort.active { background: var(--card-2); color: var(--text); }
.sortbar-right { margin-left: auto; font-size: 12px; color: var(--faint); }

.post { display: flex; background: var(--card); border: 1px solid var(--border); border-radius: var(--r); margin-bottom: 12px; overflow: hidden; scroll-margin-top: 66px; transition: border-color .15s; }
.post:hover { border-color: var(--border-hi); }
.post:target { border-color: var(--orange); }
.gutter { display: flex; flex-direction: column; align-items: center; gap: 2px; padding: 14px 6px; width: 44px; flex-shrink: 0; background: rgba(255,255,255,0.015); }
.vote { width: 18px; height: 18px; fill: var(--orange); opacity: 0.9; }
.score { font: 600 12px var(--mono); color: var(--text); }
.post-main { padding: 12px 16px 10px; min-width: 0; flex: 1; }
.post-meta { display: flex; align-items: center; gap: 7px; font-size: 12px; color: var(--dim); flex-wrap: wrap; }
.avatar { width: 20px; height: 20px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-size: 10px; font-weight: 700; color: #fff; flex-shrink: 0; }
.avatar.you { background: linear-gradient(135deg, #4fa3ff, #7c8cf8); }
.avatar.claude { background: linear-gradient(135deg, var(--claude), #ff9d6b); }
.author { font-weight: 600; color: var(--text); font-size: 12px; }
.claude-a { color: var(--claude); }
.when { font-size: 11px; color: var(--faint); }
.flair { font-size: 10.5px; font-weight: 600; padding: 2px 8px; border-radius: 999px; }
.files-flair { background: rgba(79,163,255,0.12); color: var(--blue); }
.post-title { margin: 7px 0 0; font-size: 16.5px; font-weight: 650; letter-spacing: -0.012em; line-height: 1.35; word-break: break-word; }
.post-body { margin-top: 7px; font-size: 13px; color: var(--dim); white-space: pre-wrap; word-break: break-word; }
.post-body.clamp { display: -webkit-box; -webkit-line-clamp: 5; -webkit-box-orient: vertical; overflow: hidden; }
.readmore { background: none; border: none; padding: 4px 0 0; color: var(--blue); font: 600 12px var(--sans); cursor: pointer; }
.post-actions { display: flex; gap: 4px; margin: 10px 0 4px; }
.paction { display: inline-flex; align-items: center; gap: 6px; font: 600 12px var(--sans); color: var(--dim); background: none; border: none; border-radius: 6px; padding: 5px 9px; cursor: pointer; }
.paction:not(.static):hover { background: var(--card-2); color: var(--text); }
.paction.static { cursor: default; }
.paction svg { width: 15px; height: 15px; }

.thread { margin-top: 4px; }
.thread.folded { display: none; }
.no-comments { color: var(--faint); font-size: 12.5px; padding: 8px 0; }
.comment { display: flex; gap: 0; margin-top: 8px; }
.threadline { width: 20px; flex-shrink: 0; background: none; border: none; cursor: pointer; position: relative; padding: 0; }
.threadline::before { content: ''; position: absolute; left: 9px; top: 26px; bottom: 2px; width: 2px; border-radius: 2px; background: var(--border); transition: background .12s; }
.threadline:hover::before { background: var(--orange); }
.c-main { flex: 1; min-width: 0; }
.c-meta { display: flex; align-items: center; gap: 7px; }
.c-body { font-size: 13px; margin: 5px 0 0 27px; color: var(--text); white-space: pre-wrap; word-break: break-word; max-width: 70ch; }
.comment.folded .c-body, .comment.folded .runs { display: none; }
.runs { margin: 7px 0 2px 27px; display: flex; flex-direction: column; gap: 3px; }
.run { display: flex; align-items: center; gap: 8px; padding: 4px 8px; border-radius: 8px; background: rgba(255,255,255,0.02); border: 1px solid transparent; min-width: 0; }
.run:hover { border-color: var(--border); background: var(--card-2); }
.run-i { width: 20px; height: 20px; border-radius: 6px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; background: color-mix(in srgb, var(--c) 13%, transparent); color: var(--c); }
.run-i svg { width: 11.5px; height: 11.5px; }
.run-tool { font-size: 12px; font-weight: 600; flex-shrink: 0; }
.run-n { font-size: 10.5px; font-weight: 600; color: var(--c); flex-shrink: 0; }
.run-d { font-size: 11px; color: var(--dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.rail { position: sticky; top: 66px; display: flex; flex-direction: column; gap: 14px; max-height: calc(100vh - 80px); overflow-y: auto; scrollbar-width: thin; }
.card { background: var(--card); border: 1px solid var(--border); border-radius: var(--r); overflow: hidden; }
.card-head { padding: 11px 16px; font-size: 11.5px; font-weight: 700; letter-spacing: 0.07em; text-transform: uppercase; color: var(--dim); border-bottom: 1px solid var(--border); }
.accent-head { background: linear-gradient(90deg, rgba(255,69,0,0.14), transparent 70%); color: var(--text); }
.card-pad { padding: 14px 16px; }
.card-pad.tight { padding: 8px 12px; }
.about-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px 8px; }
.about-row { display: flex; flex-direction: column; }
.about-v { font-size: 16px; font-weight: 700; letter-spacing: -0.01em; font-variant-numeric: tabular-nums; }
.about-l { font-size: 11px; color: var(--dim); }

.sparksvg { width: 100%; height: 56px; display: block; }
.spark-axis { display: flex; justify-content: space-between; font-size: 10px; color: var(--faint); margin-top: 5px; }

.frow { display: grid; grid-template-columns: 18px minmax(0,1fr) 56px 30px; gap: 8px; align-items: center; padding: 5px 4px; border-radius: 6px; }
.frow:hover { background: var(--card-2); }
.frank { font-size: 10px; color: var(--faint); }
.fname { font-size: 11.5px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.fspark { height: 5px; background: var(--card-2); border-radius: 3px; overflow: hidden; }
.fspark i { display: block; height: 100%; background: linear-gradient(90deg, var(--orange), #ff8717); border-radius: 3px; }
.fcount { font-size: 10.5px; color: var(--dim); text-align: right; }
.more-note { font-size: 11px; color: var(--faint); padding: 6px 4px 2px; }

.mixbar { display: flex; height: 10px; border-radius: 5px; overflow: hidden; gap: 1px; }
.mixbar i { display: block; height: 100%; min-width: 3px; }
.mixlegend { display: flex; flex-wrap: wrap; gap: 5px 12px; margin-top: 11px; }
.lg { display: inline-flex; align-items: center; gap: 6px; font-size: 11.5px; color: var(--dim); }
.lg i { width: 7px; height: 7px; border-radius: 50%; }
.lg b { color: var(--text); font-weight: 600; }
.rail-foot { font-size: 11.5px; color: var(--faint); padding: 2px 4px; }

.tip { position: fixed; z-index: 60; pointer-events: none; max-width: 400px; padding: 7px 11px; background: #1e242a; border: 1px solid var(--border-hi); border-radius: 8px; font-size: 12px; line-height: 1.45; box-shadow: 0 10px 28px rgba(0,0,0,0.5); }

@media (max-width: 900px) {
  .shell { grid-template-columns: 1fr; }
  .rail { position: static; max-height: none; order: -1; }
  .fakesearch { display: none; }
}
`;
}

/* ------------------------------------ js ------------------------------------ */

function js() {
  return `
const tip = document.getElementById('tip');
let tipEl = null;
document.addEventListener('mouseover', e => {
  const t = e.target.closest('[data-tip]');
  if (t && t !== tipEl) { tipEl = t; tip.textContent = t.getAttribute('data-tip'); tip.hidden = false; }
  else if (!t && tipEl) { tipEl = null; tip.hidden = true; }
});
document.addEventListener('mousemove', e => {
  if (tip.hidden) return;
  const pad = 14; let x = e.clientX + pad, y = e.clientY + pad;
  const r = tip.getBoundingClientRect();
  if (x + r.width > innerWidth - 8) x = e.clientX - r.width - pad;
  if (y + r.height > innerHeight - 8) y = e.clientY - r.height - pad;
  tip.style.left = x + 'px'; tip.style.top = y + 'px';
});
document.addEventListener('click', e => {
  const fold = e.target.closest('[data-fold]');
  if (fold) { fold.parentElement.classList.toggle('folded'); return; }
  const col = e.target.closest('[data-collapse]');
  if (col) { document.getElementById(col.getAttribute('data-collapse'))?.classList.toggle('folded'); return; }
  const ex = e.target.closest('[data-expand]');
  if (ex) {
    const p = ex.previousElementSibling;
    p.classList.toggle('clamp');
    ex.textContent = p.classList.contains('clamp') ? 'Read more' : 'Show less';
    return;
  }
  const sort = e.target.closest('[data-sort]');
  if (sort) {
    document.querySelectorAll('.sort').forEach(b => b.classList.remove('active'));
    sort.classList.add('active');
    const feed = document.getElementById('posts');
    const posts = [...feed.children];
    if (sort.getAttribute('data-sort') === 'top') posts.sort((a, b) => (+b.dataset.ops) - (+a.dataset.ops));
    else posts.sort((a, b) => +a.id.slice(1) - +b.id.slice(1));
    posts.forEach(p => feed.appendChild(p));
  }
});
`;
}

/* ---------------------------------- helpers ---------------------------------- */

function splitPrompt(text) {
  const t = String(text ?? '').trim();
  const nl = t.indexOf('\n');
  if (nl === -1) {
    if (t.length <= 140) return { title: t, body: '' };
    return { title: t.slice(0, 139) + '…', body: t };
  }
  const first = t.slice(0, nl).trim();
  const title = first.length <= 140 ? first : first.slice(0, 139) + '…';
  return { title, body: t.slice(nl + 1).trim() };
}

function communityName(sourcePath) {
  if (!sourcePath) return 'session';
  const parts = String(sourcePath).split('/').filter(Boolean);
  const dir = parts.length >= 2 ? parts[parts.length - 2] : 'session';
  const cleaned = dir.replace(/^-Users-[^-]+-?/, '').replace(/^-+|-+$/g, '');
  return (cleaned || 'session').slice(0, 40);
}

function offsetLabel(ts, t0) {
  const t = Date.parse(ts);
  if (!Number.isFinite(t) || !Number.isFinite(t0)) return '·';
  const s = Math.max(0, Math.round((t - t0) / 1000));
  if (s < 60) return `+${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `+${m}m ${s % 60}s`;
  return `+${Math.floor(m / 60)}h ${m % 60}m`;
}

function summarizeArgs(tool, args) {
  if (!args || typeof args !== 'object') return '';
  if (args.file_path) return args.file_path;
  if (args.path) return args.path;
  if (args.command) return args.command;
  if (args.pattern) return args.pattern;
  if (args.query) return args.query;
  if (args.prompt) return args.prompt;
  if (args.url) return args.url;
  const first = Object.entries(args)[0];
  return first ? `${first[0]}=${String(first[1])}` : '';
}

function compact(n) {
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, '') + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, '') + 'k';
  return String(n);
}

function shortPath(p) {
  const parts = String(p).split('/').filter(Boolean);
  if (parts.length <= 2) return p;
  return parts.slice(-2).join('/');
}

function truncate(s, n) {
  s = String(s);
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function basename(p) {
  if (!p) return '';
  return String(p).split('/').pop();
}

function formatDate(ts) {
  const d = new Date(ts);
  if (isNaN(d)) return String(ts);
  return d.toLocaleString(undefined, { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function formatClock(t) {
  const d = new Date(t);
  if (isNaN(d)) return '';
  return d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' });
}

function formatDuration(start, end) {
  if (!start || !end) return '—';
  const ms = Date.parse(end) - Date.parse(start);
  if (!Number.isFinite(ms) || ms < 0) return '—';
  const s = Math.floor(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${s % 60}s`;
  return `${Math.floor(m / 60)}h ${m % 60}m`;
}

function flame() {
  return '<svg viewBox="0 0 16 16" fill="currentColor"><path d="M8 1.5c.4 2.2-.6 3.4-1.6 4.5C5.3 7.1 4.2 8.3 4.2 10.2a3.8 3.8 0 0 0 7.6 0c0-1.3-.5-2.3-1.1-3.2-.2.5-.6 1-1.1 1.3.3-2.4-.5-5.2-1.6-6.8Z"/></svg>';
}

function bolt() {
  return '<svg viewBox="0 0 16 16" fill="currentColor"><path d="M9.5 1 3 9h3.5L6 15l6.5-8H9Z"/></svg>';
}

function bubble() {
  return '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M2.5 3.5h11v7h-6l-3 2.8V10.5h-2Z" stroke-linejoin="round"/></svg>';
}

function UP_SVG() {
  return `<svg viewBox="0 0 16 16" fill="currentColor">${UP}</svg>`;
}
